#!/usr/bin/env python3
"""
Regenerate src/lib/images.generated.ts from what is actually on disk.

Scans public/work/<project>/ for hero.webp and numbered stills, reads their
real dimensions, and merges the video lists: scraped ones from
scripts/readymag-media.json and hand written ones from
scripts/manual-media.json.

Run after adding, removing, or replacing any project media:

    python3 scripts/build-media.py
"""

import json
import os
import re
import glob
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK = os.path.join(ROOT, "public", "work")
SCRAPED = os.path.join(ROOT, "scripts", "readymag-media.json")
MANUAL = os.path.join(ROOT, "scripts", "manual-media.json")
OUT = os.path.join(ROOT, "src", "lib", "images.generated.ts")


def load(path):
    if not os.path.exists(path):
        return {}
    with open(path) as fh:
        return json.load(fh)


def scraped_videos(entry):
    """Normalise the Readymag video shape, dropping duplicates."""
    out, seen = [], set()
    for v in entry.get("videos") or []:
        provider = (v.get("provider") or "").lower()
        if provider == "youtube" and v.get("vid"):
            item = {
                "provider": "youtube",
                "id": v["vid"],
                "url": f"https://youtu.be/{v['vid']}",
                "title": v.get("title") or "",
            }
        elif provider == "vimeo":
            m = re.search(r"vimeo\.com/(\d+)", v.get("url") or "")
            if not m:
                continue
            item = {
                "provider": "vimeo",
                "id": m.group(1),
                "url": v["url"],
                "title": v.get("title") or "",
            }
        else:
            continue
        key = (item["provider"], item["id"])
        if key in seen:
            continue
        seen.add(key)
        out.append(item)
    return out


def main():
    scraped = load(SCRAPED)
    manual = load(MANUAL)
    manifest = {}

    projects = sorted(
        {d for d in os.listdir(WORK) if os.path.isdir(os.path.join(WORK, d))}
        | {k for k in manual if not k.startswith("_")}
    )

    for slug in projects:
        folder = os.path.join(WORK, slug)

        gallery = []
        for path in sorted(glob.glob(os.path.join(folder, "*.webp"))):
            name = os.path.basename(path)
            if name == "hero.webp":
                continue
            w, h = Image.open(path).size
            gallery.append({"src": f"/work/{slug}/{name}", "w": w, "h": h})

        hero = None
        hero_path = os.path.join(folder, "hero.webp")
        if os.path.exists(hero_path):
            w, h = Image.open(hero_path).size
            hero = {"src": f"/work/{slug}/hero.webp", "w": w, "h": h}
        elif gallery:
            # No dedicated hero file, so the first still leads.
            hero = gallery[0]

        videos = scraped_videos(scraped.get(slug, {}))
        videos += [v for v in (manual.get(slug, {}).get("videos") or [])]

        manifest[slug] = {"hero": hero, "gallery": gallery, "videos": videos}

    body = json.dumps(manifest, indent=2)
    ts = f"""// AUTO-GENERATED by scripts/build-media.py. Do not edit by hand.

export interface Img {{ src: string; w: number; h: number }}
export interface Vid {{
  provider: 'youtube' | 'vimeo' | 'tiktok';
  id: string;
  url: string;
  title: string;
}}
export interface Entry {{ hero: Img | null; gallery: Img[]; videos: Vid[] }}

export const images: Record<string, Entry> = {body} as const;
"""
    with open(OUT, "w") as fh:
        fh.write(ts)

    imgs = sum(len(v["gallery"]) for v in manifest.values())
    vids = sum(len(v["videos"]) for v in manifest.values())
    print(f"{len(manifest)} projects, {imgs} images, {vids} videos -> {OUT}")


if __name__ == "__main__":
    main()
